### ISSUE TITLE
Función que pinte las pistas

### ISSUE THREAD

**Issue by oneeyedman** [Adalab/dorcar-s2-evaluacion-intermedia-SandraCGarcia#3]
Ahora mismo pintamos a maneto cada pista cuando toca... no sería guay hacernos una función a la que le pasásemos por parámetro el texto de la pista y ella se ocupase de pintarlo donde toca?

Sí, sí que sería guay

![Aw yeah](https://media.giphy.com/media/WuZ2Yb29Z3J72/giphy.gif)

**Comment by SandraCGarcia** [comment]
Listo! si le echas un ojo m dices si está bien planteado porque funcionar, lo que es funcionar.... FUNCIONA!!
[](https://media.giphy.com/media/mIZ9rPeMKefm0/giphy.gif
)

**Comment by SandraCGarcia** [comment]
LISTO! si le echas un ojo ya me dirás si está bien planteado porque funcionar, lo que es funcionar... FUNCIONA!!

https://media.giphy.com/media/mIZ9rPeMKefm0/giphy.gif

**Comment by oneeyedman** [comment]
Pero sigo viendo que usas `pista.innerHTML= "Ganador";`. Tendrías que hacer una función a la que le pasases el texto como parámetro y te pintase la pista.

**Comment by oneeyedman** [comment]
Estupendo!
