### ISSUE TITLE
Vamos a actualizar el ejercicio con la base de gulp que os preparamos!

### ISSUE THREAD

**Issue by oneeyedman** [Adalab/dorcar-s2-evaluacion-intermedia-SandraCGarcia#4]
A partir de ahora, para este repo, cada issue debes resolverlo en una rama. Cuando esté resuelto haz un commit siguiendo [estas indicaciones](https://blog.github.com/2013-01-22-closing-issues-via-commit-messages/) y lanza un pull request y me pones como revisor. Cuando lo revise, tú lo podrás mergear y se autocerrará el issue :)

Te parece?

**Comment by SandraCGarcia** [comment]
cool :)
